from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.conditions import IfCondition
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue


def typed(name, value_type):
    return ParameterValue(LaunchConfiguration(name), value_type=value_type)


def generate_launch_description():
    args = [
        DeclareLaunchArgument("node_name", default_value="mcl"),
        DeclareLaunchArgument("use_sensor_points_merger", default_value="false"),
        DeclareLaunchArgument("map_yaml_file", default_value="/tmp/dist_map.yaml"),
        DeclareLaunchArgument("localization_mode", default_value="2"),
        DeclareLaunchArgument("measurement_model_type", default_value="3"),
        DeclareLaunchArgument("map_frame", default_value="map"),
        DeclareLaunchArgument("odom_frame", default_value="odom"),
        DeclareLaunchArgument("base_link_frame", default_value="base_link"),
        DeclareLaunchArgument("laser_frame", default_value="velodyne"),
        DeclareLaunchArgument("opt_pose_frame", default_value="opt_pose"),
        DeclareLaunchArgument("sensor_points_name", default_value="/velodyne_points"),
        DeclareLaunchArgument("odom_name", default_value="/odom"),
        DeclareLaunchArgument("imu_name", default_value="/gpsimu_driver/imu_data"),
        DeclareLaunchArgument("use_odom", default_value="false"),
        DeclareLaunchArgument("use_imu", default_value="false"),
        DeclareLaunchArgument("particles_name", default_value="/particles"),
        DeclareLaunchArgument("opt_particles_name", default_value="/optimized_particles"),
        DeclareLaunchArgument("pose_name", default_value="/mcl_pose"),
        DeclareLaunchArgument("opt_pose_name", default_value="/opt_pose"),
        DeclareLaunchArgument("imu_sample_freq", default_value="200.0"),
        DeclareLaunchArgument("voxel_leaf_size", default_value="1.0"),
        DeclareLaunchArgument("particle_num", default_value="1000"),
        DeclareLaunchArgument("sensor_points_num", default_value="1000"),
        DeclareLaunchArgument("z_hit", default_value="0.9"),
        DeclareLaunchArgument("z_rand", default_value="0.05"),
        DeclareLaunchArgument("z_max", default_value="0.05"),
        DeclareLaunchArgument("var_hit", default_value="0.4"),
        DeclareLaunchArgument("range_reso", default_value="0.1"),
        DeclareLaunchArgument("range_max", default_value="120.0"),
        DeclareLaunchArgument("unknown_lambda", default_value="0.001"),
        DeclareLaunchArgument("broadcast_tf", default_value="true"),
        DeclareLaunchArgument("use_odom_tf", default_value="false"),
        DeclareLaunchArgument("use_linear_interpolation", default_value="true"),
        DeclareLaunchArgument("random_particle_rate", default_value="0.1"),
        DeclareLaunchArgument("resample_threshold", default_value="0.5"),
        DeclareLaunchArgument("opt_max_iter_num", default_value="30"),
        DeclareLaunchArgument("opt_max_error", default_value="0.5"),
        DeclareLaunchArgument("convergence_threshold", default_value="0.02"),
        DeclareLaunchArgument("optimized_particle_num", default_value="1000"),
        DeclareLaunchArgument("optimized_pose_cov_coef", default_value="1.0"),
        DeclareLaunchArgument("gmm_postion_var", default_value="0.3"),
        DeclareLaunchArgument("gmm_angle_var", default_value="0.1"),
        DeclareLaunchArgument("ahrs_filter_kp", default_value="0.0"),
        DeclareLaunchArgument("ahrs_filter_ki", default_value="0.0"),
        DeclareLaunchArgument("use_initial_pose_cb", default_value="true"),
        DeclareLaunchArgument("log_file", default_value="/tmp/mcl3d_log.txt"),
        DeclareLaunchArgument("write_log", default_value="true"),
    ]

    static_tf = Node(
        name="base_link_to_laser",
        package="tf2_ros",
        executable="static_transform_publisher",
        arguments=[
            "--x", "0",
            "--y", "0",
            "--z", "0",
            "--roll", "0",
            "--pitch", "0",
            "--yaw", "0",
            "--frame-id",
            LaunchConfiguration("base_link_frame"),
            "--child-frame-id",
            LaunchConfiguration("laser_frame"),
        ],
    )

    merger = Node(
        name="sensor_points_merger",
        package="mcl3d_ros",
        executable="sensor_points_merger",
        condition=IfCondition(LaunchConfiguration("use_sensor_points_merger")),
    )

    localizer = Node(
        name=LaunchConfiguration("node_name"),
        package="mcl3d_ros",
        executable="mcl",
        output="screen",
        parameters=[{
            "map_yaml_file": LaunchConfiguration("map_yaml_file"),
            "sensor_points_name": LaunchConfiguration("sensor_points_name"),
            "odom_name": LaunchConfiguration("odom_name"),
            "imu_name": LaunchConfiguration("imu_name"),
            "particles_name": LaunchConfiguration("particles_name"),
            "opt_particles_name": LaunchConfiguration("opt_particles_name"),
            "pose_name": LaunchConfiguration("pose_name"),
            "opt_pose_name": LaunchConfiguration("opt_pose_name"),
            "map_frame": LaunchConfiguration("map_frame"),
            "odom_frame": LaunchConfiguration("odom_frame"),
            "base_link_frame": LaunchConfiguration("base_link_frame"),
            "laser_frame": LaunchConfiguration("laser_frame"),
            "opt_pose_frame": LaunchConfiguration("opt_pose_frame"),
            "use_odom": typed("use_odom", bool),
            "use_imu": typed("use_imu", bool),
            "broadcast_tf": typed("broadcast_tf", bool),
            "use_odom_tf": typed("use_odom_tf", bool),
            "use_initial_pose_cb": typed("use_initial_pose_cb", bool),
            "use_linear_interpolation": typed("use_linear_interpolation", bool),
            "imu_sample_freq": typed("imu_sample_freq", float),
            "localization_mode": typed("localization_mode", int),
            "measurement_model_type": typed("measurement_model_type", int),
            "particle_num": typed("particle_num", int),
            "sensor_points_num": typed("sensor_points_num", int),
            "random_particle_rate": typed("random_particle_rate", float),
            "resample_threshold": typed("resample_threshold", float),
            "z_hit": typed("z_hit", float),
            "z_rand": typed("z_rand", float),
            "z_max": typed("z_max", float),
            "var_hit": typed("var_hit", float),
            "range_reso": typed("range_reso", float),
            "unknown_lambda": typed("unknown_lambda", float),
            "range_max": typed("range_max", float),
            "voxel_leaf_size": typed("voxel_leaf_size", float),
            "opt_max_iter_num": typed("opt_max_iter_num", int),
            "opt_max_error": typed("opt_max_error", float),
            "convergence_threshold": typed("convergence_threshold", float),
            "optimized_particle_num": typed("optimized_particle_num", int),
            "optimized_pose_cov_coef": typed("optimized_pose_cov_coef", float),
            "gmm_postion_var": typed("gmm_postion_var", float),
            "gmm_angle_var": typed("gmm_angle_var", float),
            "ahrs_filter_kp": typed("ahrs_filter_kp", float),
            "ahrs_filter_ki": typed("ahrs_filter_ki", float),
            "log_file": LaunchConfiguration("log_file"),
            "write_log": typed("write_log", bool),
            "initial_pose": [0.0, 0.0, 0.0, 0.0, 0.0, 90.0],
            "base_link_2_laser": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            "initial_noise": [0.1, 0.1, 0.1, 0.05, 0.05, 0.05],
            "odom_noise": [
                0.5, 0.01, 0.01, 0.01, 0.01, 0.01,
                0.01, 0.5, 0.01, 0.01, 0.01, 0.01,
                0.01, 0.01, 0.5, 0.01, 0.01, 0.01,
                0.01, 0.01, 0.01, 0.5, 0.01, 0.01,
                0.01, 0.01, 0.01, 0.01, 0.5, 0.01,
                0.01, 0.01, 0.01, 0.01, 0.01, 0.5,
            ],
            "resample_noise": [0.1, 0.1, 0.1, 0.05, 0.05, 0.05],
        }],
    )

    return LaunchDescription(args + [static_tf, merger, localizer])
